### ISSUE TITLE
Unpacked only names

### ISSUE THREAD

**Issue by imKota** [crskycode/BGI_Script_Tool#2]
Hello @crskycode!

i found bug:)

Export text
`BGI_Script_Tool.exe -e 01_prologue01`

only names

![image](https://user-images.githubusercontent.com/24241471/123524947-2cece480-d6d6-11eb-9b87-e79e92dcd6eb.png)

Export all text
`BGI_Script_Tool.exe -a 01_prologue01`

![image](https://user-images.githubusercontent.com/24241471/123524970-658cbe00-d6d6-11eb-871a-ee8511ed98bb.png)

[01_prologue01.zip](https://github.com/crskycode/BGI_Script_Tool/files/6720652/01_prologue01.zip)

**Comment by crskycode** [comment]
The script uses an opcode `push_string` to load strings, there is no better way to distinguish them.
Use `-a` option to export all strings. 😐
See [this](https://github.com/crskycode/BGI_Script_Tool/blob/990c46282a752c3dcd68738b23f71af8080e1b5c/Script.cs#L158)
You can also write some rules to filter strings.

**Comment by imKota** [comment]
> The script uses an opcode `push_string` to load strings, there is no better way to distinguish them.
> Use `-a` option to export all strings. 😐
> See [this](https://github.com/crskycode/BGI_Script_Tool/blob/990c46282a752c3dcd68738b23f71af8080e1b5c/Script.cs#L158)
> You can also write some rules to filter strings.


Okay I used `-a`, but that doesn't work either.
Since line 73 is empty, it is not possible to compile changes to the script
Okay, but that doesn't work either.

![image](https://user-images.githubusercontent.com/24241471/123540131-12525400-d746-11eb-9244-722493e29bd5.png)

**Comment by crskycode** [comment]
You can delete all empty lines (use RegEx). 🙂
Of course, I recommend that you change the source code to make it suitable for your work.

**Comment by imKota** [comment]
> You can delete all empty lines (use RegEx). 🙂
> Of course, I recommend that you change the source code to make it suitable for your work.

So you don’t want to fix your utility?:D

**Comment by crskycode** [comment]
> > You can delete all empty lines (use RegEx). 🙂
> > Of course, I recommend that you change the source code to make it suitable for your work.
> 
> So you don’t want to fix your utility?:D

Fixed.
New Release [Here](https://github.com/crskycode/BGI_Script_Tool/releases/tag/1.1)

**Comment by imKota** [comment]
> Fixed.
> New Release [Here](https://github.com/crskycode/BGI_Script_Tool/releases/tag/1.1)

Thanks for the fix :)

Hmm, strange. 
Rebuild working only for folders, it's normal?

**Comment by crskycode** [comment]
> > Fixed.
> > New Release [Here](https://github.com/crskycode/BGI_Script_Tool/releases/tag/1.1)
> 
> Thanks for the fix :)
> 
> Hmm, strange.
> Rebuild working only for folders, it's normal?

Working with `file` or `folder`, make sure `script` and `script.txt` in same folder.
New script will created in `rebuild` folder.

**Comment by imKota** [comment]
@crskycode thanks!
