### ISSUE TITLE
Extract error?

### ISSUE THREAD

**Issue by fushi002** [crskycode/BGI_Script_Tool#3]
Hello @crskycode
I am informing you that there is a bug in your tool
If you extract the file below, 
[https://mega.nz/file/ahogkJxD#kHzybffQTtb8Z_jXK-TkhlJJanBetZuZeAM4MuD4f8M](url)

this is the result.
![image](https://user-images.githubusercontent.com/88200209/168007931-50215062-6187-4a56-9752-4b0ce1183eec.png)

10,16,22 lines seem to be abnormal extraction

The normal file is printed as follows:
![image](https://user-images.githubusercontent.com/88200209/168008853-81c30348-d3b7-43dd-8fd9-51137812f8a2.png)

I was curious about the source of that unusual sentence, so I searched it and found it on line 7612.
![image](https://user-images.githubusercontent.com/88200209/168009136-c09f8d49-89a3-42ed-a4ed-120a68aa65a8.png)
Of course, because of that unusual sentence, there was an error even when rebuild.

**Comment by crskycode** [comment]
This tool extracts text in a quick search mode, so errors are possible. Delete error lines and try rebuild.

**Comment by fushi002** [comment]
> This tool extracts text in a quick search mode, so errors are possible. Delete error lines and try rebuild.

![image](https://user-images.githubusercontent.com/88200209/168020336-e2c357ed-908a-4a07-9901-1819fe8aa6e3.png)

Is it correct to correct it like this?
However, the error still occurs

**Comment by crskycode** [comment]
Ignore all text that does not contain Japanese  ( don't use `-a` mode ). Then find all broken lines, delete them.
You can also use other tools.

**Comment by fushi002** [comment]
OK.
I extracted in -e mode and the following result came out.
![image](https://user-images.githubusercontent.com/88200209/168084473-b0580e46-239e-4200-a4f8-ccfdc7a95cba.png)

And after modifying it as follows, it was rebuilt
(Rebuild only works with folders, is this normal? Of course, the script file and the script text file were placed in the same location. However, the rebuild folder was not created normally, and it was created only when it was placed in the folder.)
![image](https://user-images.githubusercontent.com/88200209/168084888-00261d45-b3f1-4f81-afa3-19c554471ecc.png)

Anyway,
There was still an error, and when I checked the rebuilt file with another tool, I could see that the three lines that were deleted were still there.
![image](https://user-images.githubusercontent.com/88200209/168087881-9eb59bfd-a74e-40f1-b57c-5c45ecc61962.png)

Although there are many BGI tools, there was no tool that was as easy to handle as the BGI tool you made by you.
I hope the error will be corrected.
Thank you.

**Comment by fushi002** [comment]
I want you to correct the tool, and I report another extraction error that I found in the past.

The file below is part of a file that outputs several random words out of dozens of words.
https://drive.google.com/drive/folders/1tfAndPxTDFNUY2snci5XamWp3F_K1ZzY?usp=sharing

If you extract it,
◆000021B8◆健康グッズ

It is extracted only up to there, and the extraction is not normal after that.
I think only about one-third of the entire sentence is extracted.
(Not optional -a)

This error I found is only a small fraction of thousands of test files, and your tool generally works well.

I hope this tool will get better.

**Comment by Cosetto** [comment]
https://github.com/arcusmaximus/VNTranslationTools your choice @fushi002 
dump to json 
![image](https://user-images.githubusercontent.com/81801486/168781152-87a9d130-e4c4-4186-91f3-23d5f4b2963b.png)
or dump to xlsx
![image](https://user-images.githubusercontent.com/81801486/168781300-5c3d72e0-e817-4549-8e8f-1c16364d7e4f.png)

**Comment by fushi002** [comment]
Thank you for the information
